version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: main
  groups:
    dev-dependencies:
      patterns:
        - "*"
